version: '2'
services:
    mysqldev:
        image: mysql:5.6
        restart: always
        volumes:
            - ./dev-mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
        networks:
            - dev
    phpmyadmin:
        depends_on:
            - mysqldev
        image: phpmyadmin/phpmyadmin:4.6
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysqldev
            MYSQL_ROOT_PASSWORD: password
        networks:
            - dev
    wordpress:
        build:
            ./apache
        depends_on:
            - mysqldev
        volumes:
            - ./apache/html:/var/www/html
        environment:
            WORDPRESS_DB_HOST: mysqldev:3306
            WORDPRESS_DB_PASSWORD: password
        ports:
            - 80:80
        networks:
            - dev
networks:
    dev:
